version: '3.8'

services:
  mynewapp-db:
    image: mysql:8
    container_name: mynewapp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mynewappdb
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Kolkata
    ports:
      - "3307:3306"
    networks:
      - app-network

  mynewapp:
    image: geethar27/springapp:latest  # rebuild for new project
    container_name: mynewapp
    depends_on:
      - mynewapp-db
    restart: always
    ports:
      - "9091:80"
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mynewapp-db:3306/mynewappdb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      TZ: Asia/Kolkata

networks:
  app-network:
    driver: bridge
