version: '3.8'

services:
  clicknbuy-db-new:
    image: mysql:8
    container_name: clicknbuy-db-new
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clicknbuy_new
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Kolkata
    ports:
      - "3307:3306"
    networks:
      - app-network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 20

  springapp-new:
    image: geethar27/springapp:latest
    container_name: springapp-new
    restart: always
    depends_on:
      clicknbuy-db-new:
        condition: service_healthy

    ports:
      - "9091:80"

    networks:
      - app-network

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://clicknbuy-db-new:3306/clicknbuy_new?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      TZ: Asia/Kolkata

networks:
  app-network:
    driver: bridge
